### ISSUE TITLE
Why do this?

### ISSUE THREAD

**Issue by macmichael01** [rooseveltframework/roosevelt-uglify#100]
Assuming this is an on the fly js compiler middleware. I hope my assumption is correct. 

In my past experience with other frameworks that do this very thing, I found that is not a positive experience. Compiling on the fly, whether that involves removal of whitespace, variable renaming or some other advanced compilation to your js code comes at the cost of performance (especially as a project grows and multiple engineers are working on it).

Secondly, if there are any typos or syntax errors when code gets compiled results may fail to properly render. This type of work should happen once not every time. Even, if you support caching results, then developers would have to worry about cache invalidation. A wise person once told me, the 2 hardest problems in computer science is cache invalidation, naming things, and off-by-1 errors ;)

My suggestion is use a build tool for these types of things such as grunt or gulp rather than adding a build tool into the app that serves up your code. My ideal app or service backend or frontend should be both lean and mean. Anyways that's my 2 cents! Cheers!

**Comment by kethinov** [comment]
Roosevelt's CSS/JS compiler build system does not compile at runtime. It compiles when the application starts. It then caches the minified files into a build folder for use during the life of the app before starting the server. Cache is invalidated when both of these conditions are met: 1. the app is restarted, and 2. the source files have changed since the last restart. You can also manually clear the cache by running `npm run clean`.

As for conflating the build system with the app, this is an intentional design decision to simplify the architecture for developers. Rather than having a separate command to build the app and then another to run it e.g. `npm run build` and then `npm start`, we have simplified it down to a single command and builds are only done when the source code is stale enough to need it. This reduces unnecessary complexity and lowers the learning curve, which is the whole point of the project: to be the easiest backend framework to learn and use in the Node.js ecosystem.

In service of that goal, we are explicitly trying to prevent developers from ever having to touch gulp or grunt. It isn't quite right to refer to them as build systems. It's more accurate to say they're task runners that let you code your own build system. And coding your own build system for every app you make is probably not a good use of time most of the time.

That said, if for whatever reason you have build needs that Roosevelt's simpler, declarative build system doesn't address, you can always simply disable it and use gulp/grunt. Roosevelt doesn't preclude that.

**Comment by macmichael01** [comment]
My question for why do this is a design question not a question I had about the framework.

Whether it compiles during the start of the application or during runtime it's still performing an unnecessary task. This should be abstracted away. This is why build tools or if we would rather call them task runners, were created (refer to my 2 hardest CS problems joke).

Take for example, a native applications on Mac OS, Windows, etc.. when launching an app, would you design it to compile code when a user chooses to launch an application or should it be compiled down to a place that focuses on speed, performance, and error reduction? There are some lessons we can learn from the Adobe products and their use of unnecessary splash screens to launch their applications. if its not needed pull it out. Building an application at the launch as a built in is something an external tool should focus on.

I would take some time to investigate the points that I am trying to point out to you. I've had some pretty less than optimal experiences over the years with doing on the fly style code compression whether handled at launch or during runtime.
